version: '3.0'
services:
  aiplatform:
    build: .
    ports:
      - 4000:80
      - 4100:4100

  db:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: 5432

  rest:
    image: postgrest/postgrest:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always
    environment:
        PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
        PGRST_DB_SCHEMA: public
        PGRST_DB_ANON_ROLE: postgres
        PGRST_JWT_SECRET: super-secret-jwt-token