apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aicollaboration.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - aicollaboration.com
    - '*.aicollaboration.com'
    secretName: aicollaboration-com-tls
  - hosts:
    - aicollaboration.net
    - '*.aicollaboration.net'
    secretName: aicollaboration-net-tls
  rules:
  - host: aicollaboration.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  - host: aicollaboration.net
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  
