apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aicollaboration.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - aicollaboration.com
      secretName: tls-latest-aiproduct.io
  rules:
    - host: aicollaboration.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80