apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aicollaboration.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - aicollaboration.net
    - aicollaboration.com
    - aiproduct.io
    secretName: tls-latest-aiproduct.io
  rules:
  - host: aicollaboration.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: frontend
            port: 80
  - host: aicollaboration.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: frontend
            port: 80
  - host: aiproduct.io
    http:
      paths:
      - path: /
        backend:
          service:
            name: frontend
            port: 80
