name: Frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  
  deploy:
     runs-on: ubuntu-latest
    
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Shell
        run: |
	  pwd
	  sed -i "s/<latest>/${{ github.sha }}/g" charts/values.yaml
	  
      - name: Set kubernetes secrets
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
	  
	  
      - name: k8s deployment
        run: |
          helm upgrade --install aiplatform-frontend charts -f charts/values.yaml
          helm list
          
	  
          
          
	 
         
          
