name: Frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  
  deploy:
     runs-on: ubuntu-latest
    
    
     steps:
      - name: Checkout
        uses: actions/checkout@v2
         
      - name: Set kubernetes secrets
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Shell
        run: |
          sed -i "s/<VERSION>/${{ github.sha }}/g" devops/kubernetes/deployment-solution.yml

      - name: k8s deployment
        run: |
          kubectl apply -f devops/kubernetes/api-ingress-solution.yml
          kubectl apply -f devops/kubernetes/deployment-solution.yml
          kubectl apply -f devops/kubernetes/service-solution.yml
          kubectl apply -f devops/kubernetes/certificate.yml
